#:schema https://cloudflare.github.io/wrangler-schema/config.schema.json
name = "singbox-profiles"
main = "src/index.js"
compatibility_date = "2024-01-27" 

# --- [云端保密室绑定] ---
# 告诉 Worker：把刚才创建的 KV 空间接入进来，在代码里称呼它为 "DB"
[[kv_namespaces]]
binding = "DB"
id = "a31d1c58df5449358358d59dce21b456"
